"""Gemini-backed authenticity detector (the default backend).

A dedicated, focused pass — separate from the adjudication "brain" so it can be tuned and
swapped independently. For each image it asks Gemini whether the photo is a genuine
camera capture or AI-generated / digitally manipulated, returning a calibrated confidence
and short signals. Assess one image per call so a verdict is unambiguous and cacheable by
content hash via `MemoizingAuthenticityDetector`.

Uses `gemini-2.5-flash` by default (override with CLAIMREVIEW_AUTH_MODEL). The SDK is
imported lazily so the package works without `google-genai` installed.
"""

from __future__ import annotations

import base64
import json

from claimreview.authenticity.detector import AuthenticityDetector, ImageAuthenticity
from claimreview.io.images import LoadedImage

DEFAULT_MODEL = "gemini-2.5-flash"
MAX_OUTPUT_TOKENS = 300
# ai_likelihood at/above this is treated as "AI-generated" for the boolean verdict.
AI_DECISION = 0.5

SYSTEM_PROMPT = (
    "You are a forensic image-authenticity analyst screening photos submitted with insurance "
    "damage claims. Judge AUTHENTICITY ONLY — not the damage. Some images ARE AI-generated by "
    "modern diffusion models that can look very realistic, so do not assume realism means real.\n\n"
    "Actively scrutinize for synthetic / manipulation cues: over-smooth or plastic textures, "
    "fabricated or garbled fine detail (screws, seams, badges, text/logos), physically impossible "
    "reflections or shadows, inconsistent lighting, too-perfect symmetry, diffusion/GAN noise, "
    "cloning or splicing seams.\n\n"
    "Genuine claim photos are often imperfect (blurry, dim, cropped) — imperfection alone is NOT "
    "evidence of AI. Output JSON: ai_likelihood (0.0-1.0 CALIBRATED probability the image is "
    "AI-generated or manipulated; do NOT default to 0 — give your honest estimate), signals "
    "(array of <=4 short phrases naming the strongest cues you saw, empty if none)."
)


def parse_verdict(image_id: str, text: str) -> ImageAuthenticity:
    """Parse the model JSON into an ImageAuthenticity (defensive against bad output).

    The model returns a calibrated `ai_likelihood`; we expose it as `confidence` and derive
    the boolean `ai_generated` at AI_DECISION. `apply_authenticity` then applies the (higher)
    action threshold, so likelihood doubles as the confidence the policy gates on.
    """
    try:
        d = json.loads(text or "{}")
    except (ValueError, TypeError):
        d = {}
    try:
        likelihood = float(d.get("ai_likelihood", 0.0))
    except (ValueError, TypeError):
        likelihood = 0.0
    likelihood = max(0.0, min(1.0, likelihood))
    signals = d.get("signals") or []
    if not isinstance(signals, list):
        signals = [str(signals)]
    return ImageAuthenticity(
        image_id, likelihood >= AI_DECISION, likelihood, [str(s) for s in signals][:4]
    )


def _response_schema():
    from google.genai import types

    return types.Schema(
        type=types.Type.OBJECT,
        properties={
            "ai_likelihood": types.Schema(type=types.Type.NUMBER),
            "signals": types.Schema(
                type=types.Type.ARRAY, items=types.Schema(type=types.Type.STRING)
            ),
        },
        required=["ai_likelihood", "signals"],
        property_ordering=["ai_likelihood", "signals"],
    )


class GeminiAuthenticityDetector(AuthenticityDetector):
    name = "gemini"

    def __init__(self, api_key: str, model: str | None = None) -> None:
        from google import genai

        self._client = genai.Client(api_key=api_key)
        self.model = model or DEFAULT_MODEL

    def _assess_one(self, image: LoadedImage) -> ImageAuthenticity:
        from google.genai import types

        parts = [
            types.Part.from_text(text="Assess this single image's authenticity."),
            types.Part.from_bytes(data=base64.b64decode(image.data_b64), mime_type=image.mime_type),
        ]
        response = self._client.models.generate_content(
            model=self.model,
            contents=[types.Content(role="user", parts=parts)],
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                temperature=0,
                max_output_tokens=MAX_OUTPUT_TOKENS,
                # Disable "thinking": it silently consumes the output budget and yields empty
                # responses (FinishReason.MAX_TOKENS) for this short structured task.
                thinking_config=types.ThinkingConfig(thinking_budget=0),
                response_mime_type="application/json",
                response_schema=_response_schema(),
            ),
        )
        return parse_verdict(image.image_id, response.text)

    def assess(self, images: list[LoadedImage]) -> list[ImageAuthenticity]:
        return [self._assess_one(img) for img in images]
